### ISSUE TITLE
Improper label: "ICE 2: description of risk in informed consent form"

### ISSUE THREAD

**Issue by fjmanion** [ICO-ontology/ICO#14]
ICO_0000008 has this strange label starting with "ICE 2: " which I assume simply meant it was classified on someone's spreadsheet as an information content entity before it was imported into protege. 

Can we get this fixed? There really is nothing else wrong with the term.

 If we had a clear release process for ICO I could do it. I think this issue also implies we need a clearly agreed on and documented release process.

**Comment by yongqunh** [comment]
This has been fixed. The words "ICE 2: " are removed from this label.
