### ISSUE TITLE
NTR: 'consent for postmortem donation of specified anatomical entities’ 

### ISSUE THREAD

**Issue by cstoeckert** [ICO-ontology/ICO#8]
Needed by OBIB for a NCI Biorepositories and Biospecimen Research Branch request. For one of their studies they were trying to evaluate normal tissue from non-diseased people. This means that the tissues came from people who died unexpectedly (e.g., accidental deaths, suicides, homicides).  The consent came from the surviving families of the donor - consent by family member after death. A form listing the specified tissues/ fluids was used to verify consent for each.
Suggested definition:  a standing declaration to allow postmortem collection of specimens derived from specified anatomical entities that is the outcome of an informed consent process that occurs after death of the donor and has donor family members as participants.

**Comment by cstoeckert** [comment]
include a logical axiom to 'material anatomical entity' so that the tissue/fluid can be specified. Not sure what is best relation though. Maybe we can discuss on next call.

**Comment by cstoeckert** [comment]
discussed on June 22, 2017 OBIB call. Not a standing declaration, but could be a document act. Not the outcome of an informed consent process. has participant 'material anatomical entity'

label: consent for postmortem donation of specified anatomical entities
definition: a document act to allow postmortem collection of specimens derived from specified anatomical entities that is the outcome of a process that occurs after death of the donor in consultation with donor family members.
axiom: 'document act' and has participant some 'material anatomical entity'

**Comment by zhengj2007** [comment]
term added

see commit: https://github.com/ICO-ontology/ICO/commit/494b4d438c451ba2bc12779af4920380723b04e8
