### ISSUE TITLE
my ICO experience

### ISSUE THREAD

**Issue by leipzig** [ICO-ontology/ICO#9]
I recently attempted to digitize an existing consent for a Genomics Research & Innovation Network exome study (see the result [here](https://github.com/leipzig/consent_ontology/blob/master/grin.owl)).

I found ICO pretty good at categorizing fairly large swathes of the consent using Protégé but I am still left wondering if ICO can really be used to make consents _computable_ or even _comparable_.

Are there other examples of ICO digitized consents I can examine?

**Comment by linikujp** [comment]
Hi Jeremy,

Can you explain what do you mean by "make consents computable"? In what
sense, you will think they should be considered as computable. Or in a
simpler word, do you have an example?

Thanks,
Asiyah, one of the ICO developers.

**Comment by leipzig** [comment]
So by computable I mean how does one query a consent against scenarios - what the patient has agreed to and where the data can be reused.

**Comment by linikujp** [comment]
This is the final goal ICO wanted to achieve. For now ICO doesn't have this
capacity. More work needs to be done to get to that point.
The use case you are working can be a good use case for expanding ICO. We
could work together on this if you are interested.
If you have real data (filled consent forms), the consent form needs to be
break down and fill into the ontology. And then you could run a sparql
query.

Secondly, you could look at the VICO paper and the ontology to get an idea
of using ICO. However, the VICO eventually focused on the questionnaire but
not the consent itself.
https://github.com/VICO-ontology/VICO
https://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-016-0062-4

Thanks,
Asiyah

**Comment by leipzig** [comment]
Great - I think GRIN could be a decent example to work with. Let's take this offline - I'll contact you directly.
